### ISSUE TITLE
Can’t download newer versions of `traefik-plugins/traefik-jwt-plugin` plugin

### ISSUE THREAD

**Issue by sturman** [traefik/plugin-service#63] opened 2024-11-21 21:26 UTC
For example, the following URL works fine...

    https://plugins.traefik.io/public/download/github.com/traefik-plugins/traefik-jwt-plugin/v0.8.2

...but anything above that version yields a "404 This page could not be found." message...

    https://plugins.traefik.io/public/download/github.com/traefik-plugins/traefik-jwt-plugin/v0.9.0

Tested with these curl commands on Hetzner Cloud server
```bash
curl https://plugins.traefik.io/public/download/github.com/traefik-plugins/traefik-jwt-plugin/v0.8.2 # responds with binary file which is expected
curl https://plugins.traefik.io/public/download/github.com/traefik-plugins/traefik-jwt-plugin/v0.9.0 # responds with 404 and html
```
Screenshot of a page in response ![Image](https://github.com/user-attachments/assets/493cd26b-5079-4879-9322-f4d1cc5dc658)

Similar issue #62

**Comment by sturman** [comment] 2024-11-25 18:19
Hi @mmatur,
Could you please take a look on this issue? 

Here are `cf-ray` response header examples:
```
< cf-ray: 8e8399a55d071da8-FRA
< cf-ray: 8e839e4be8b6364a-FRA
< cf-ray: 8e839ed4ff1b366e-FRA
```

**Comment by mloiseleur** [comment] 2024-11-26 09:35
Hello @sturman,

Thanks for your report. It seems to be a duplicate of https://github.com/traefik/traefik/issues/11298, so I close this one.

Feel free to re-open if I missed something.

**Closed by mloiseleur** 2024-11-26 09:35 UTC
